theme: jekyll-theme-minimal
title: Probabilités et statistiques pour la biologie (cours AMU SBBAU16L - STAT1)
description: Cours du Master en Bioinformatique, Biochimie Structurale et Génomique (BBSG) d'Aix-Marseille Université (AMU)