---
title: 'CMB-STAT2 : Statistics for Biology'
author: "Jacques van Helden"
date: '`r Sys.Date()`'
output:
  html_document:
    fig_caption: yes
    highlight: zenburn
    theme: cerulean
    toc: yes
    toc_depth: 3
    toc_float: yes
  beamer_presentation:
    colortheme: dolphin
    fig_caption: yes
    fig_height: 6
    fig_width: 7
    fonttheme: structurebold
    highlight: tango
    incremental: no
    keep_tex: no
    slide_level: 2
    theme: Montpellier
    toc: yes
  pdf_document:
    fig_caption: yes
    highlight: zenburn
    toc: yes
    toc_depth: 3
  slidy_presentation:
    fig_caption: yes
    fig_height: 6
    fig_width: 7
    highlight: tango
    incremental: no
    keep_md: yes
    smaller: yes
    theme: cerulean
    toc: yes
    widescreen: yes
    self_contained: no
  ioslides_presentation:
    colortheme: dolphin
    fig_caption: yes
    fig_height: 6
    fig_width: 7
    fonttheme: structurebold
    highlight: tango
    incremental: yes
    keep_md: yes
    smaller: yes
    theme: cerulean
    toc: yes
    widescreen: yes
  revealjs::revealjs_presentation:
    theme: night
    transition: none
    self_contained: true
    css: ../slides.css
---

```{r include=FALSE, echo=FALSE, eval=TRUE}
options(width = 300)
knitr::opts_chunk$set(
  fig.width = 7, fig.height = 5, 
  fig.path = 'figures/01_intro_',
  fig.align = "center", 
  size = "tiny", 
  echo = TRUE, eval = TRUE, 
  warning = FALSE, message = FALSE, 
  results = TRUE, comment = "")
```


## General info

- AMU code: [S53MA2Z2B](https://formations.univ-amu.fr/ME5SBI-S53MA2Z2B-en.html)
- 6h lectures + 6h exercises + 6h practicals
- Teachers

    - 2019-2020: **Jacques van Helden**
    
- Students

    - [M1 Computational and Mathematical Biology, Master Bioinformatique](https://formations.univ-amu.fr/ME5SBI-PRSBI5AA.html)
    - [M1 Computational and Mathematical Biology, Master Master Mathématiques et applications](https://formations.univ-amu.fr/ME5SMA-PRSMA5AF.html)
    - [M1 Computational and Mathematical Biology, Master Mathématiques appliquées, statistique](https://formations.univ-amu.fr/ME5SMS-PRSMS5AD.html)

- Links

    - Web site: <https://jvanheld.github.io/stat1/CMB-STAT2.md>
    - Github repository: <https://github.com/jvanheld/stat1>
    - Ametice: <https://ametice.univ-amu.fr/course/view.php?id=50334>


## Prerequisites

- Students are supposd to have followed general courses of statistics and be familiar with the main concepts usually treated
- For students of the [M1 Computational and Mathematical Biology, Master Master Mathématiques et applications](https://formations.univ-amu.fr/ME5SMA-PRSMA5AF.html), this course follows the course Probabillities and statistics applied to modelling 1 (STAT1)

## Scope of the course

This course aims at providing students with a practical approach of the analysis of biological data with R, based on the concepts acquired in the course “Probabilities and statistics for modelling 1”. The associated mathematical foundations will be developed in the course “Advanced statistics”. 

The following notions will be investigated :

- Sampling and estimation (moments, robust estimators, confidence intervals)
- Fitting
- Additional distributions
- Hypothesis testing (mean comparison, goodness of fit,…)

## Study cases

1. Distribution of k-mers (oligonucleotides) in DNA sequences

2. Analysis of omics data:

    - Den Boer ML *et al.* (2009). A subtype of childhood acute lymphoblastic leukaemia with poor treatment outcome: a genome-wide classification study. Lancet Oncol. 2009 10:125-34. [[doi: 10.1016/S1470-2045(08)70339-5](http://doi.org/10.1016/S1470-2045(08)70339-5)], 
[[PMID 19138562](https://www.ncbi.nlm.nih.gov/pubmed/19138562)]. Data available at Gene Expression Omnibus, series [[GSE13425](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE13425)]


****************************************************************
## Access

- Web site: <https://jvanheld.github.io/stat1/STAT2_CMB.html>
- [**GitHub** repository](https://github.com/jvanheld/stat1) (same repo for STAT1 and STAT2)
- Shell command to get a git clone: 

    `git clone git@github.com:jvanheld/stat1.git`


****************************************************************

## Course content and supports

| Day | Contents | Type | Supports | 
|---------|------------------------------|-----------------|-----------|
| 2020-02-17 | Fitting theoretical distributions on k-mer counts | Practical | [[html](practicals/kmer_distributions/kmer_distributions.html)] [[pdf](practicals/kmer_distributions/kmer_distributions.pdf)] [[Rmd](https://raw.githubusercontent.com/jvanheld/stat1/master/practicals/kmer_distributions/kmer_distributions.Rmd)] |
|  |  | Live demo starting script | [[R](practicals/kmer_distributions/live-demo_solutions_kmer-distributions.R)] |
| 2020-02-20 | Discrete distributions | Lecture | [[html](slides/04_discrete_distributions_EN.html)] [[pdf](slides/04_discrete_distributions_EN.pdf)] [[Rmd](https://raw.githubusercontent.com/jvanheld/stat1/master/slides/04_discrete_distributions_EN.Rmd)] |
|  |  K-mer count distributions in promoters | Solutions of the practical | [[html](practicals/kmer_distributions/kmer_distributions_solutions.html)] [[pdf](practicals/kmer_distributions/kmer_distributions_solutions.pdf)] [[Rmd](https://raw.githubusercontent.com/jvanheld/stat1/master/practicals/kmer_distributions/kmer_distributions_solutions.Rmd)]  |
| |**Multivariate analysis** |  | |
| 2020-03-05 | Study case: the DenBoer 2009 dataset | Slides | [[html](practicals/multivariate-analysis_DenBoer2009/Den_Boer_use_case.html)] [[pdf](practicals/multivariate-analysis_DenBoer2009/Den_Boer_use_case.pdf)] [[Rmd](https://raw.githubusercontent.com/jvanheld/stat1/master/practicals/multivariate-analysis_DenBoer2009/Den_Boer_use_case.Rmd)] |
| | | |


## Skills expected to be acquired at the end of this course

### Practical experience of statistical concepts

- Fitting
- Convergence between distributions
- Impact of sample size
- Estimators: moments versus robust estimators
- Multiple testing


### R programming 

- Data structures

    - vector
    - factor
    - matrix
    - data.frame
    - list
    
- Functions related to the main data structures
    
    - class()
    - is.numeric(), is.integer(), is.na(), is.xxxx()
    - c()
    - vector(), matrix(), data.frame()
    - as.vector(), as.matrix(), as.data.frame()
    - unlist()
    - nrow(), ncol(), dim()
    - append(), sort(), unique()

- Handling strings

    - sub()
    - split()
    - grep()

- Getting help

    - help()
    - ?
    - ??

- Handling files and directories

    - getwd()
    - setwd()
    - dir.create()
    - list.files()

- Handling distributions of probabilities

    - The four functions for a distribution X: dX, pX, qX, rX
    - Binomial
    - Poisson
    - Hypergeometric
    - Normal
    - Student
    - Chi2

- Descriptive statistics

    - mean(), median(), mode()
    - sd(), var(), cor()
    - quantile(), IQR()

- Drawing graphs

    - plot()
    - barplot()
    - boxplot()
    - hist()

- Installing and loading R packages

    - cran
    - bioconductor
    - github

- Implementing a function

- Documenting a function

- Using the apply and related functions

- Using R classes and objects


****************************************************************
