---
title: "Personal work -- Differential analysis and multiple testing"
author: "Jacques van Helden"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    fig_caption: yes
    highlight: zenburn
    self_contained: no
    theme: cerulean
    toc: yes
    toc_depth: 3
    toc_float: yes
  beamer_presentation:
    colortheme: dolphin
    fig_caption: yes
    fig_height: 6
    fig_width: 7
    fonttheme: structurebold
    highlight: tango
    incremental: no
    keep_tex: no
    slide_level: 2
    theme: Montpellier
    toc: yes
  ioslides_presentation:
    colortheme: dolphin
    fig_caption: yes
    fig_height: 6
    fig_width: 7
    fonttheme: structurebold
    highlight: tango
    smaller: yes
    toc: yes
    widescreen: yes
  word_document:
    toc: yes
    toc_depth: '3'
  pdf_document:
    fig_caption: yes
    highlight: zenburn
    toc: yes
    toc_depth: 3
  slidy_presentation:
    fig_caption: yes
    fig_height: 6
    fig_width: 7
    highlight: tango
    incremental: no
    keep_md: yes
    smaller: yes
    theme: cerulean
    toc: yes
    widescreen: yes
font-import: http://fonts.googleapis.com/css?family=Risque
subtitle: Probabilities and statistics for modelling 1 (STAT1)
font-family: Garamond
transition: linear
---

```{r include=FALSE, echo=FALSE, eval=TRUE}
library(knitr)
options(width = 300)
knitr::opts_chunk$set(
  fig.width = 7, fig.height = 5, 
  fig.path = 'figures/02_combinatorix_',
  fig.align = "center", 
  size = "tiny", 
  echo = TRUE, eval = TRUE, 
  warning = FALSE, message = FALSE, 
  results = TRUE, comment = "")
# knitr::asis_output("\\footnotesize")

```


## Introduction

The personal work will consist in developing a workflow to run an experimental benchmark of differential analysis applied to thousands of features. 

The goal will be to acquire an empirical feeling of the impact of different parameters on the performances of differential analysis tests. 

To this purpose, we will work with artificial data produced by generating random numbers 

- following different distribiutions of probabilities (normal, Poisson), 
- with different differences between the population means
- with equal or distinct variances

We will then run different tests and compare their performances by measuring the power and false positive rates. 


## Performances of the tests

We will measure the performances of a test by running $r = 10,000$ times under $H_0$, and $r = 10,000$ times under $H_1$. 

- count the number of $FP$, $TP$, $FN$, $TN$
- summarise the result in a confusion table
- compute the derived statistics: $FPR$, $FDR$ and $Sn$



## Questions

### 1. Impact of the difference between the means

We test the impact of the actual difference between population means on the performances of the Student test. For this, generate random datasets compliant with the assumptions (normality, homoscedasticity) but with a set of increasing differences between sample means. 

In all cases, we will set the standard deviation to $\sigma = 1$.

 | $\mu_1$ | $\mu_2$ | Comment |
 |---------|---------|---------|
 | 0 | 0 | $H_0$ |
 | -0.1 | 0.1 | $H_1$ |
 | -1 | 1 | $H_1$ |
 | -10 | 10 | $H_1$ |
 
 Maybe other values if you have time and if it brings additional insight. 
 
### 2. Impact of sample size

Generate random numbers following a normal distribution, with equal variances, but with a series of different sample sizes ($n = {2, 4, 16, 64}$). 

Run Student test and evaluate the impact of sample size on the rate of false positive and power of the test. 

### 3. Impact of variance

Generate random numbers following a normal distribution, with equal sample sizes ($n_1 = n_2 = 10$), but with a series of different standard deviations ($\sigma = {0.1, 1, 10, 100}$). 

Run Student test and evaluate the impact of sample size on the rate of false positive and power of the test. 

### 4. Impact of non-normality on Student test

Generate random numbers following either a normal or a Poisson distribution. 

1a. Small samples: $n_1 = n_2 = 4$
1b. Large samples: $n_1 = n_2 = 50$

### 5. Impact of heteroscedasticity on Student test

Generate random numbers following a normal distribution with either equal or unequal variances (test different values). Run Student test on both data types, and measure the sensitivity and power of the respective tests. 

### 6. Impact of homoscedasticity on Welch test

Generate random numbers following a normal distribution with either equal or unequal variances (test different values). Run Welch test on both data types, and measure the sensitivity and power of the respective tests. 


### 7. Parametric versus non-parametric tests

Generate random numbers following a normal and some non-normal distribution of your choice (e.g. uniform). Run a parametric and a non-parametric test and compare the performances in terms fo power and false positive rate. 


## Assignation of the tasks

Each student will develop an analysis to test one particular question. 

| Student | Question |
|---------|-----------------------------|
| JvH  + you | 1. Impact of the difference between the means  |
|    |   |


## Expected results

- Descriptive statistics (explor your data): 

    - graphical representations of the data (use whatever you like: histograms, boxplots, violin plots, dot plots, ...)
    - descriptive parameters of your samples (distribution of sample means, sample sd, ...)

- Histogram of the p-values (20 bins) for all the cases under $H_0$, and under $H_1$, resp.
- Volcano plot for all the cases under $H_0$, and under $H_1$, resp.

- Indicators: $FPR$, $FDR$, $Sn$, $E-value$ for threshold values $alpha = 0.05$,  $alpha = 0.01$, ,  $alpha = 0.001$


## Report format

- R markdown (must be able to run on my machine)
- either a pdf or a self-contained HTML (preferred because easier to browse tables are better formatted)

## Structure of the report

- Introduction: explain the question addressed in your specific report, and the expected outcome of what you are testing (do you expect an increase of FP ? a loss in sensitivity ? ...).

- Setting of the experiment: write explicitly the configuration of your tests (distributions, parameters)

- Results and interpretation: summarize your results with figures and tables, document the figures and tables with detailed legends, and add an interpretation of what we see in the results section. 

- Summary and conclusion: summarize the results in 2-3 sentences and conclude about the effect you wanted to test. 











