---
title: "Tests de comparaison de moyenne"
author: "Jacques van Helden"
date: '`r Sys.Date()`'
output:
  html_document:
    fig_caption: yes
    highlight: zenburn
    theme: cerulean
    toc: yes
    toc_depth: 3
    toc_float: yes
  beamer_presentation:
    colortheme: dolphin
    fig_caption: yes
    fig_height: 6
    fig_width: 7
    fonttheme: structurebold
    highlight: tango
    incremental: no
    keep_tex: no
    slide_level: 2
    theme: Montpellier
    toc: yes
  ioslides_presentation:
    colortheme: dolphin
    fig_caption: yes
    fig_height: 6
    fig_width: 7
    fonttheme: structurebold
    highlight: tango
    incremental: no
    keep_md: no
    smaller: yes
    theme: cerulean
    toc: yes
    widescreen: yes
  pdf_document:
    fig_caption: yes
    highlight: zenburn
    toc: yes
    toc_depth: 3
  slidy_presentation:
    fig_caption: yes
    fig_height: 6
    fig_width: 7
    highlight: tango
    incremental: no
    keep_md: no
    smaller: yes
    theme: cerulean
    toc: yes
    toc_float: yes
    widescreen: yes
  word_document:
    toc: yes
    toc_depth: 3
font-import: http://fonts.googleapis.com/css ?family=Risque
font-family: Garamond
subtitle: Probabilités et statistique pour la biologie (STAT1)
address: TAGC lab, Aix-Marseille Université, France
transition: linear
---

```{r setup, include=FALSE, size="huge"}
library(knitr)
## Default parameters for displaying the slides
knitr::opts_chunk$set(
  echo = TRUE, 
  eval=TRUE, 
  fig.width = 7, 
  fig.height = 5, 
  fig.align = "center", 
  fig.path = "figures/",
  size = "tiny", 
  warning = FALSE, 
  results = TRUE, 
  message = FALSE, 
  comment = "")

dir.main <- "~/stat1"
dir.current <- file.path(dir.main, "practicals", "02_yeast_annotations")
setwd(dir.current)

```


# But de ce TP

Au cors de ce TP nous effectuerons des tests de comparaison de moyennes sur deux types de données. 

1. Données artificielles générées selon des distributions normales, soit sous hypothèse nulle ($H_0$) soit sous hypothèse alternative ($H_1$).  Ceci nous permettra de réaliser des tests dans des situations où nous connaissons les  paramètres des populations à comparer ($\mu_1$, $\mu_2$, $\sigma_1$, $\sigma_2$), en connaissant donc la réponse correcte du test. Le but de cet exercice sera de 

    - nous familiariser avec les tests de comparaison de moyenne: choix d'un test en fonction des caractéristiques des données, choix des paramètres du test, interprétation des résultats; 
    - évaluer l'adéquation des tests en fonction des types de données;
    - mesurer empiriquement les taux d'erreurs de types I et II, et vérifier s'ils correspondent aux attentes théoriques.

2. Données de transcriptome obtenues au moyen de puces à ADN (DNA microarrays) chez 190 patients souffrant de leucémies lymphoblastiques aigues (LLA), classifiées en différents groupes selon les perturbations chromosomiques (hyperploidie) ou génétiques (mutations d'un gène particulier) supposées être à l'origine du cancer. 

Le but de cette analyse sera de détecter les gènes exprimés différentiellement (***differentially expressed genes***, **DEG**) entre deux sous-types particuliers de cancer. 

****************************************
# Jeux de données artificiels

## Sous hypothèse nulle

Dans un premier temps, nous allons délibérément générer des données sous hypothèse nulle ($H_0$) c'est-à-dire en tirant des échantillons dans deux populations de taille égale. Les données seront générées dans les conditions d'applicabilité du test de Student: populations normales de variance égale. Le but de l'exercice sera de mesurer le **taux de faux posiitfs**, c'est-à-dire la proportion des tests déclarés (à tort) positifs, alors qu'il n'existe pas de différence entre les moyennes des deux populations.

### Application du test avec la fonction `t.test()`

1. Au moyen de la fonction `rnorm()`, tirez deux échantillons de taille $n_1 = n_2 = 10$ à partir de populations normales de moyennes $\mu_1 = \mu_2 = 7$ et d'écart-types $\sigma_1 = \sigma_2 = 2$. 

2. Effectuez un test de comparaison de moyenne en utilisant la fonction `t.test()`. Lisez attentivement l'aide de cette fonction, et choisissez les paramètres en tenant compte des caractéristiques de vos données. Nous effectuerons ici un test bilatéral (*two-tailed*). 

3. Interprétez le résultat de la fonction `t.test()`  (paramètres, décision, interprétation de la p-valeur). 

## Calcul manuel des statistiques de Student

1. Au moyen de la fonction R `\sum()`, calculez les paramètres de vos échantillons nécessaires au test de Student ($\bar{x}_1, \bar{x}_2, s_1, s_2$). 

2. Au moyen de cette même fonction `sum()`, calculez les estimateurs des mêmes paramètres pour les populations  ($\mu{x}_1, \mu{x}_2, \sigma_1, \sigma_2$).

3. Recalculez ces paramètres au moyen des fonctions R `mean()` et `sd()`.


**Attention**, les fonctions R `var()` et `sd()` ne calculent pas les paramètres d'échantillons ($\s^2$, $\s$) mais les estimateurs des paramètres de population  correspondants ($\hat{\sigma}^2$, $\had{\sigma}$). 

4. Sur base de ces paramètres, calculez la statistique $t_{obs}$ de Student. 

5. Avec la fonction $pt()$, calculez la p-valeur de cette valeur $t$. 

6. Interprétez les résultats (décision, interprétation de la p-valeur). 

## Mesure empirique du taux de faux-positifs

1. Répétez 1000 fois le test de Student au moyen de la fonction `t.test()` et récupérez dans deux vecteurs séparés les valeurs rapportées pour la statistique $t$ et pour la $p$ valeur. 

2. Dessinez l'histogramme des valeurs $t$ obtenues empiriquement.

3. Calculez la proportion de faux-positifs.



****************************************
# Données transcriptomiques obtenues par puces à ADN

Si vous arrivez ici, suivez ce tutoriel:

<http://pedagogix-tagc.univ-mrs.fr/ASG/practicals/microarrays_student_test/DenBoer_Student_test.html>

****************************************
